global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9997']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:9996']

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:9995']

  - job_name: 'producer-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'processor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'dlq-monitor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
